INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (1,'Buenos Aires',200,'WH01','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (2,'Rosario',70,'WH02','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (3,'Córdoba',150,'WH03','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (4,'Trelew',140,'WH04','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (5,'Mendoza',150,'WH05','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (6,'La Plata',100,'WH06','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (7,'San Miguel de Tucumán',120,'WH07','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (8,'Mar del Plata',180,'WH08','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (9,'Salta',140,'WH09','ACCEPT');
INSERT INTO wharehouse (id,city,maxLimit,name,action) VALUES (10,'Santa Fe',70,'WH10','ACCEPT');